Added filter by work role
Cyber4All/competency-client pull request #103
Opened 2023-05-10 16:04 UTC by bereketsega

This PR implements search and filter competency cards by work role in the dashboard.

Demo:

https://github.com/Cyber4All/competency-client/assets/72763770/8ed9eb64-024d-460e-9ecd-a6c2011a126d

2023-05-10 16:36 UTC, Cwagne17 reviewed
After talking to Mike, add the clear filters functionality. The comment on the secondary-nav.component.html has more comments.

2023-05-12 14:21 UTC, JosueMolinaMorales reviewed
Just chris' comment

2023-05-19 11:35 UTC, mfranz1 requested changes

2023-05-19 11:35 UTC, mfranz1 commented on src/app/dashboard/dashboard.component.ts
> +            }
```suggestion
            this.loadedCompetencies.push(comp);
```
The API should handle this filtering for us. We would pass the search query and that would return the results list with the correct competencies. Also, you should be able to select more than one workrole, it would be an aggregation of competencies with either workrole

2023-05-30 15:18 UTC, pmanal1 reviewed
Looks great. Just address Mike's comment

2023-05-30 18:37 UTC, JosueMolinaMorales approved these changes
Just Mike's comment

2023-05-30 18:42 UTC, Cwagne17 approved these changes

2023-06-07 17:59 UTC, bereketsega commented on src/app/dashboard/dashboard.component.ts
> +            }
The API can now handle the filtering.
[111](https://github.com/Cyber4All/competency-api/pull/111).
Selecting multiple workrole is possible also.

2023-06-08 15:33 UTC, mfranz1 approved these changes
Great job on this!

2023-06-12 13:25 UTC, merged