Replaced textareas with TinyMCE rich text editors
Cyber4All/competency-client pull request #142
Opened 2024-02-09 18:24 UTC by ksmartin301

competency-builder > components

![FireShot Capture 012 - CompetencyClient - localhost](https://github.com/Cyber4All/competency-client/assets/110073931/e512af71-9eb4-4bf6-9505-336db521797d)
![FireShot Capture 013 - CompetencyClient - localhost](https://github.com/Cyber4All/competency-client/assets/110073931/0c6b9e74-3991-4fb7-b89f-98281fe65450)
![FireShot Capture 014 - CompetencyClient - localhost](https://github.com/Cyber4All/competency-client/assets/110073931/6fcbeb0f-adea-4a19-85c5-6a6b99e5db77)
![FireShot Capture 015 - CompetencyClient - localhost](https://github.com/Cyber4All/competency-client/assets/110073931/a1f0e6ce-74c5-4e9a-9ae5-170f653ab7bd)
![FireShot Capture 016 - CompetencyClient - localhost](https://github.com/Cyber4All/competency-client/assets/110073931/f5934876-af63-41fe-99db-8473e92f8e27)
![FireShot Capture 017 - CompetencyClient - localhost](https://github.com/Cyber4All/competency-client/assets/110073931/2dcc41a4-f3e3-481d-b3e9-b5d51e130beb)
![FireShot Capture 018 - CompetencyClient - localhost](https://github.com/Cyber4All/competency-client/assets/110073931/aa195e83-a33e-47d4-89c4-a93a6734a18a)

2024-02-09 18:31 UTC, ksmartin301 reviewed
![FireShot Capture 020 - CompetencyClient - localhost](https://github.com/Cyber4All/competency-client/assets/110073931/31510f9b-891e-464b-b48d-16527f466991)
![FireShot Capture 021 - CompetencyClient - localhost](https://github.com/Cyber4All/competency-client/assets/110073931/1702d16a-2a3d-47b1-9fbf-d2d73c0361b6)

2024-02-12 15:31 UTC, JosueMolinaMorales requested changes
Looks really good. Just some questions/comments

2024-02-12 15:31 UTC, JosueMolinaMorales commented on .vscode/settings.json
This file and folder can be removed

2024-02-12 15:31 UTC, JosueMolinaMorales commented on src/app/shared/components/competency-builder/components/context-builder/context-builder.component.html
> +            [ngModelOptions]="{ standalone: true }"></editor>
Is there a way to abstract this out into its own component to reduce the code duplication?

2024-02-12 15:31 UTC, JosueMolinaMorales commented on src/app/shared/components/competency-builder/components/degree-builder/degree-builder.component.html
> +        icons: 'material',
This `apiKey` can be stored in a global constant

2024-02-12 15:31 UTC, JosueMolinaMorales commented on src/app/shared/components/competency-builder/components/employability-builder/employability-builder.component.html
> +    [formControl]="details"></textarea> -->
Did we just want to remove this old code? and not just leave it commented out

2024-02-12 20:09 UTC, bereketsega reviewed
Just Sway's comment

2024-02-13 13:16 UTC, mfranz1 commented on src/app/shared/components/competency-builder/components/employability-builder/employability-builder.component.html
> +    [formControl]="details"></textarea> -->
+1 yee, any old code should be removed please

2024-02-13 13:24 UTC, mfranz1 requested changes
Good work on this!

2024-02-13 13:24 UTC, mfranz1 commented on .vscode/settings.json
Check in a file called `.gitignore`, this file should be be in there, or at least `.vscode/*`

2024-02-13 13:24 UTC, mfranz1 commented on src/app/shared/components/competency-builder/components/actor-builder/actor-builder.component.html
> +  <!-- TinyMCE box-->
```suggestion
```
Not needed b/c of `<!--Actor description form field-->` above

2024-02-13 13:24 UTC, mfranz1 commented on src/app/shared/components/competency-builder/components/context-builder/context-builder.component.html
> +          <!-- TinyMCE box-->
```suggestion
```

2024-02-13 13:24 UTC, mfranz1 commented on src/app/shared/components/competency-builder/components/degree-builder/degree-builder.component.html
> +          <!-- TinyMCE box-->
```suggestion
```

2024-02-13 13:24 UTC, mfranz1 commented on src/app/shared/components/competency-builder/components/notes-builder/notes-builder.component.html
> +    <!-- TinyMCE box-->
```suggestion
```

2024-02-14 15:02 UTC, Cwagne17 commented on .vscode/settings.json
Then you'll also have to remove the .vscode dir from commit history. Easiest way is to remove the dir then add/commit/push and it should fix so next time it can't be staged.

2024-02-14 15:06 UTC, Cwagne17 approved these changes

2024-02-14 15:06 UTC, Cwagne17 commented on src/app/shared/components/competency-builder/components/actor-builder/actor-builder.component.html
> +    apiKey="3fkli5rzzx1lcmqsbo8n6kok6ym0yc67wdpek4h1j37jg47q"
What is the apiKey for? Did we create this or was it created for us? What does it give access to?

2024-02-14 15:06 UTC, Cwagne17 commented on src/app/shared/components/competency-builder/components/actor-builder/actor-builder.component.html
> +    apiKey="3fkli5rzzx1lcmqsbo8n6kok6ym0yc67wdpek4h1j37jg47q"
I spoke with @mfranz1 and @pzalep1. This value is not sensitive.

2024-02-14 15:18 UTC, Greek approved these changes
lgtm apart from the other comments

2024-02-26 12:52 UTC, katieblomquist approved these changes
After those changes, this looks good to me!

2024-03-06 15:18 UTC, mfranz1 approved these changes

2024-03-06 16:59 UTC, shanioffe approved these changes
Great job!

2024-03-29 14:06 UTC, merged