Feature/sc 18907/implement admin dashboard in cc client
Cyber4All/competency-client pull request #95
Opened 2023-05-04 20:15 UTC by pmanal1

[18907](https://app.shortcut.com/clarkcan/story/18907/implement-admin-dashboard-in-cc-client)

Integrates all the changes in the client to create an admin dashboard.

Several notes:
- In the mocks, each competency card has a button in the top-right corner, denoted "..." I've removed that since the 3 options in the mocks are redundant or not allowed (Edit, Change Status, and Delete). Let me know if I should implement this.
- The submitted date on each competency card will not be displayed until our infrastructure supports handling that sort of data. The story for this has been updated in the development planning board
- Filtering functionality is not implemented, a story should be created to complete this in the admin and author dashboard
- Searching functionality is not implemented a story should be created to complete this in the admin and author dashboard

## Demo Video

https://user-images.githubusercontent.com/93054689/236316020-42eab960-8e3a-4b10-aeaf-8a8b62c9cd0f.mov

## Responsive Views

### Tablet

![Screen Shot 2023-05-04 at 4 11 46 PM](https://user-images.githubusercontent.com/93054689/236318482-c5cf3a20-c45f-496f-ab61-467cafd22b00.png)

![Screen Shot 2023-05-04 at 4 12 14 PM](https://user-images.githubusercontent.com/93054689/236318549-c89dfa44-3a05-4dad-aee9-b1a492b5d606.png)

### 1024p

![Screen Shot 2023-05-04 at 4 12 41 PM](https://user-images.githubusercontent.com/93054689/236318649-efd164f1-9e19-4080-ba58-f3e4d2a559ad.png)

### 1440p

![Screen Shot 2023-05-04 at 4 13 01 PM](https://user-images.githubusercontent.com/93054689/236318710-a10cc24a-945a-4809-992f-9574efdbb7bb.png)

![Screen Shot 2023-05-04 at 4 13 45 PM](https://user-images.githubusercontent.com/93054689/236318887-7354c3e4-fa68-4af2-85d2-537034354e8b.png)

### 4K

![Screen Shot 2023-05-04 at 4 13 24 PM](https://user-images.githubusercontent.com/93054689/236318785-8d859330-448a-4813-a19b-b74dc8d03f41.png)

2023-05-08 16:20 UTC, bereketsega approved these changes
namaste! 🙏

2023-05-08 16:43 UTC, Maliyaa requested changes
Great work Paulo! I just commented some shmall tings I was curious about 😎

2023-05-08 16:43 UTC, Maliyaa commented on src/app/admin-dashboard/admin-dashboard.component.html
> +  <cc-search-bar></cc-search-bar>
There is no content in between these tags. Are they necessary?

2023-05-08 16:43 UTC, Maliyaa commented on src/app/admin-dashboard/admin-dashboard.component.ts
> +        status: [ // TODO: Remove drafts, display deprecated
Was this TODO already completed? I don't see "drafts" here.

2023-05-08 16:43 UTC, Maliyaa commented on src/app/admin-dashboard/admin-dashboard.component.ts
> +    await sleep(1000);
Is this necessary?

2023-05-08 16:43 UTC, Maliyaa commented on src/app/admin-dashboard/admin-dashboard.component.ts
> +  async deleteCompetency(competencyId: string) {
Is this after rejecting or deprecating?

2023-05-08 16:43 UTC, Maliyaa commented on src/app/admin-dashboard/admin-dashboard.component.ts
> +   * Method to open the competency-card component and build a competency
Just have a personal preference for these JDOCS. They could be more specific because admins aren't building a competency. They would only be editing, approving, or deprecating.

2023-05-08 17:00 UTC, mfranz1 requested changes
Good stuff, I do have some changes.

```
In the mocks, each competency card has a button in the top-right corner, denoted "..." I've removed that since the 3 options in the mocks are redundant or not allowed (Edit, Change Status, and Delete). Let me know if I should implement this.
```
Out of scope? I'm fine if it get's broken out into it's own component/directive story

```
The submitted date on each competency card will not be displayed until our infrastructure supports handling that sort of data. The story for this has been updated in the development planning board
```
👍 whiner
```
Filtering functionality is not implemented, a story should be created to complete this in the admin and author dashboard
```
👍 yeetamos
```
Searching functionality is not implemented a story should be created to complete this in the admin and author dashboard
```
👍 now you're killing me

2023-05-09 13:54 UTC, Cwagne17 commented on src/app/admin-dashboard/admin-dashboard.component.html
> +  <cc-search-bar></cc-search-bar>
It refers to a component (search-bar)

2023-05-09 14:01 UTC, Cwagne17 requested changes

2023-05-11 12:22 UTC, pzalep1 commented on src/app/admin-dashboard/admin-dashboard.component.ts
> +    await sleep(1000); // TODO: Do we need this?
I think this was from an original implementation.

2023-05-11 12:22 UTC, pzalep1 commented on src/app/admin-dashboard/admin-dashboard.component.ts
> +        // author: this.authService.user?._id, // TODO: Display from any user
^

2023-05-11 12:22 UTC, pzalep1 commented on src/app/admin-dashboard/admin-dashboard.component.ts
> +  async openCompetencyBuilder(existingCompetency?: Competency) {
Yes, there are cases where they might need to.

2023-05-11 12:25 UTC, pzalep1 reviewed
Just a few comments.

2023-05-19 18:04 UTC, pmanal1 commented on src/app/admin-dashboard/admin-dashboard.component.ts
> +        status: [ // TODO: Remove drafts, display deprecated
yes, it's been removed.

2023-05-19 18:23 UTC, pmanal1 commented on src/app/admin-dashboard/admin-dashboard.component.ts
> +   * Method to open the competency-card component and build a competency
Comment changed to `Method to open the preview-competency component and edit a submitted competency`

2023-05-19 18:37 UTC, pmanal1 commented on src/app/admin-dashboard/admin-dashboard.component.ts
> +        // author: this.authService.user?._id, // TODO: Display from any user
Nope, I'll remove it!

2023-05-19 18:58 UTC, pmanal1 commented on src/app/admin-dashboard/admin-dashboard.component.ts
> +    // this.filterCompetencies.emit({
Yes, it wasn't implemented right, so I've fixed it.

2023-05-19 19:22 UTC, pmanal1 commented on src/entity/Competency.ts
> +        limit:${query?.limit ?? 0}, ${query?.author ? `\nauthor: "${query?.author}",` : ''}
Yes, if this search query has an author passed in, it will add `author: query?.author` to the GraphQL query. This change accounts for the problem when sending an empty string to the author query. The API checks if it is a valid mongo id, and will throw an error on an empty string, when the behavior we want is to ignore the author all-together if we pass in an empty string

Long story short, this avoids that error by removing the author query if it's not passed in. It does look weird and is quite difficult to read, lmk if I should add a comment on this or change something to make it look nicer

2023-05-30 12:43 UTC, Cwagne17 approved these changes

2023-05-30 13:07 UTC, mfranz1 approved these changes
Great work!

2023-05-30 18:38 UTC, JosueMolinaMorales approved these changes

2023-05-31 19:21 UTC, merged